## COPYING/SORTING/RESHAPING

In [1]:
import numpy as np

In [2]:
array = np.random.randint(1,20,15)
array

array([ 6,  8, 17,  6, 16, 16, 16,  7,  2, 18,  8, 17, 16, 15,  8])

In [3]:
a = np.random.randint(1,20,(2,4))
a

array([[ 4,  8,  5, 10],
       [10, 17, 17, 17]])

In [3]:
array.data

### Copy

Return an array copy of the given object.


In [4]:
array

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

In [5]:
array1 = array
array1

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

In [ ]:
array1 = np.copy(array)
array1

### Sort

Return a sorted copy of an array.

In [11]:
np.sort(array)

array([ 1,  1,  2,  4,  7,  9, 10, 10, 11, 11, 14, 15, 16, 19, 19])

In [ ]:
array.sort()

In [ ]:
array

### Transpose

Transposes arr (rows become columns and
vice versa

In [7]:
matrix = np.random.randint(0,15,(5,3))
matrix

array([[ 6,  0,  4],
       [11,  5,  0],
       [ 6,  5,  9],
       [12,  5,  7],
       [ 2,  9,  0]])

In [12]:
matrix.T

array([[ 6, 11,  6, 12,  2],
       [ 0,  5,  5,  5,  9],
       [ 4,  0,  9,  7,  0]])

### Reshape

Returns an array containing the same data with a new shape.

In [13]:
array

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

In [14]:
array.ndim

1

In [15]:
array.reshape((3,5))

array([[11,  9,  4,  2,  1],
       [ 7, 19, 14,  1, 16],
       [19, 10, 11, 15, 10]])

In [16]:
array.reshape((5,3))

array([[11,  9,  4],
       [ 2,  1,  7],
       [19, 14,  1],
       [16, 19, 10],
       [11, 15, 10]])

## ADDING/REMOVING ELEMENTS

### append

Append values to the end of an array.

In [17]:
array

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

In [18]:
np.append(array,20)

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10, 20])

### Insert

Insert values along the given axis before the given indices.

In [19]:
np.insert(array,2,25)

array([11,  9, 25,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

### Delete

Return a new array with sub-arrays along an axis deleted.

In [20]:
np.delete(array,3)

array([11,  9,  4,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

In [21]:
matrix

array([[ 6,  0,  4],
       [11,  5,  0],
       [ 6,  5,  9],
       [12,  5,  7],
       [ 2,  9,  0]])

In [22]:
np.delete(matrix,3,axis=0) # Deletes row on index 3 of arr

array([[ 6,  0,  4],
       [11,  5,  0],
       [ 6,  5,  9],
       [ 2,  9,  0]])

In [23]:
np.delete(matrix,2,axis=1) # Deletes column on index 4 of arr

array([[ 6,  0],
       [11,  5],
       [ 6,  5],
       [12,  5],
       [ 2,  9]])

## COMBINING/SPLITTING

In [24]:
arr1 = np.random.randint(1,10,5)
arr1

array([2, 9, 7, 9, 9])

In [25]:
arr2 = np.random.randint(1,10,5)
arr2

array([3, 8, 4, 3, 7])

### Concatenate

Join a sequence of arrays along an existing axis.

In [26]:
np.concatenate((arr1,arr2),axis=0) # Adds arr2 as rows to the end of arr1

array([2, 9, 7, 9, 9, 3, 8, 4, 3, 7])

In [27]:
arr1 = np.random.randint(1,4,(2,2))
arr1

array([[3, 3],
       [3, 2]])

In [28]:
arr2 = np.random.randint(1,4,(2,2))
arr2

array([[2, 1],
       [1, 3]])

In [29]:
np.concatenate((arr1,arr2),axis=1) # Adds arr2 as columns to end of arr1

array([[3, 3, 2, 1],
       [3, 2, 1, 3]])

### Split

In [30]:
matrix

array([[ 6,  0,  4],
       [11,  5,  0],
       [ 6,  5,  9],
       [12,  5,  7],
       [ 2,  9,  0]])

In [31]:
np.split(matrix,5,axis=0)

[array([[6, 0, 4]]),
 array([[11,  5,  0]]),
 array([[6, 5, 9]]),
 array([[12,  5,  7]]),
 array([[2, 9, 0]])]

## SCALAR MATH

In [33]:
array

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

### add

Add arguments element-wise.

In [34]:
np.add(array,2)
#array + 2

array([13, 11,  6,  4,  3,  9, 21, 16,  3, 18, 21, 12, 13, 17, 12])

### Substract

Subtract arguments, element-wise.

In [35]:
np.subtract(array,2)

array([ 9,  7,  2,  0, -1,  5, 17, 12, -1, 14, 17,  8,  9, 13,  8])

### Multiply

Multiply arguments element-wise.

In [36]:
np.multiply(array,2)

array([22, 18,  8,  4,  2, 14, 38, 28,  2, 32, 38, 20, 22, 30, 20])

### Divide

Returns a true division of the inputs, element-wise.

In [37]:
array

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

In [38]:
np.divide(array,2)

array([5.5, 4.5, 2. , 1. , 0.5, 3.5, 9.5, 7. , 0.5, 8. , 9.5, 5. , 5.5,
       7.5, 5. ])

### Power

First array elements raised to powers from second array, element-wise.

In [39]:
array

array([11,  9,  4,  2,  1,  7, 19, 14,  1, 16, 19, 10, 11, 15, 10])

In [40]:
np.power(array,2)

array([121,  81,  16,   4,   1,  49, 361, 196,   1, 256, 361, 100, 121,
       225, 100], dtype=int32)

## VECTOR MATH


In [41]:
arr1

array([[3, 3],
       [3, 2]])

In [42]:
arr2

array([[2, 1],
       [1, 3]])

In [43]:
np.add(arr1,arr2)

array([[5, 4],
       [4, 5]])

In [44]:
arr1 + arr2

array([[5, 4],
       [4, 5]])

In [45]:
np.subtract(arr1,arr2)

array([[ 1,  2],
       [ 2, -1]])

In [46]:
np.multiply(arr1,arr2)

array([[6, 3],
       [3, 6]])

In [47]:
np.divide(arr1,arr2)

array([[1.5       , 3.        ],
       [3.        , 0.66666667]])

In [48]:
print(arr1)
print(arr2)

[[3 3]
 [3 2]]
[[2 1]
 [1 3]]


In [49]:
np.power(arr1,arr2)

array([[9, 3],
       [3, 8]], dtype=int32)

In [50]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081],
       [1.73205081, 1.41421356]])

In [51]:
np.sin(arr1)

array([[0.14112001, 0.14112001],
       [0.14112001, 0.90929743]])

In [52]:
np.cos(arr1)

array([[-0.9899925 , -0.9899925 ],
       [-0.9899925 , -0.41614684]])

In [53]:
np.log(arr1)

array([[1.09861229, 1.09861229],
       [1.09861229, 0.69314718]])

### Ceil

Roundup to the next greatest integer

In [54]:
arr = np.array([2.5,3.9,4,1.2])
arr

array([2.5, 3.9, 4. , 1.2])

In [55]:
np.ceil(arr)

array([3., 4., 4., 2.])

### floor

Roundup to next least integer

In [ ]:
arr

In [56]:
np.floor(arr)

array([2., 3., 4., 1.])

### Round

Round an array to the given number of decimals.

In [57]:
np.round(arr,2)

array([2.5, 3.9, 4. , 1.2])

## Statistics

In [58]:
arr1

array([[3, 3],
       [3, 2]])

In [59]:
np.mean(arr1)

2.75

In [62]:
np.mean(arr1,axis=1) #  Column wise mean

array([3. , 2.5])

In [63]:
np.mean(arr1,axis=0) # Row wise mean

array([3. , 2.5])

In [64]:
arr1.sum()

11

In [65]:
arr1.min()

2

In [66]:
arr1.max()

3

In [67]:
np.var(arr1)

0.1875

In [68]:
np.std(arr1)

0.4330127018922193

In [69]:
np.std(arr1,axis=0) # Row wise std

array([0. , 0.5])

In [70]:
np.std(arr1,axis=1) # Column wise std

array([0. , 0.5])

### Dot

Dot product of two arrays.

In [71]:
arr1

array([[3, 3],
       [3, 2]])

In [72]:
arr2

array([[2, 1],
       [1, 3]])

In [73]:
arr1.dot(arr2)

array([[ 9, 12],
       [ 8,  9]])

In [74]:
arr1 * arr2

array([[6, 3],
       [3, 6]])

## SUBSRTTING

### comparision Operators

In [76]:
matrix

array([[ 6,  0,  4],
       [11,  5,  0],
       [ 6,  5,  9],
       [12,  5,  7],
       [ 2,  9,  0]])

In [77]:
matrix > 5

array([[ True, False, False],
       [ True, False, False],
       [ True, False,  True],
       [ True, False,  True],
       [False,  True, False]])

In [78]:
matrix[matrix > 5]

array([ 6, 11,  6,  9, 12,  7,  9])

In [79]:
matrix[matrix==6]

array([6, 6])

In [80]:
matrix[matrix!=5]

array([ 6,  0,  4, 11,  0,  6,  9, 12,  7,  2,  9,  0])

In [81]:
matrix[(matrix>5) & (matrix < 10)]

array([6, 6, 9, 7, 9])

In [82]:
matrix[(matrix >5) | (matrix <12 )]

array([ 6,  0,  4, 11,  5,  0,  6,  5,  9, 12,  5,  7,  2,  9,  0])