# NumPy operations

Operations or Computation on NumPy arrays can be very fast, or it can be very slow. The key to
making it fast is to use **vectorized operations**, generally implemented through Num‐
Py’s universal functions (ufuncs).

Ufuncs exist in two flavors:
- **unary ufuncs**, which operate on a single input.
- **binary ufuncs**, which operate on two inputs. 

We’ll see examples of both these types of functions here.

##  Array Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:


In [ ]:
import numpy as np
arr = np.arange(0,10)
arr

#### Arithemetic for array with scalar


In [ ]:
arr + 5

In [ ]:
arr - 5

In [ ]:
arr * 5

In [ ]:
arr**2

In [ ]:
arr % 2

In [ ]:
arr /2

In [ ]:
np.add(arr,2)

#### Arithmetic for array with array

In [ ]:
arr

In [ ]:
arr + arr

In [ ]:
arr - arr

In [ ]:
arr * arr

In [ ]:
arr/arr

In [ ]:
arr % arr

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
# Taking abosulte values

x = np.array([-2, -1, 0, 1, 2])
print(x)
print(abs(x))

In [ ]:
#Calcualting exponential (e^),2 to th power of x and 3 to the power of x.
x = np.array([2,3,4])
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

In [ ]:
# natural, base-2 logarithm or the base-10 logarithm.

x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

#### Aggregations:


In [ ]:
arr

In [ ]:
np.max(arr)

In [ ]:
np.min(arr)

In [ ]:
np.sum(arr)

In [ ]:
np.mean(arr)

In [ ]:
np.std(arr)

In [ ]:
np.var(arr)

#### Multidimensional Aggregates:

In [ ]:
arr = np.array([[2,3,5],[1,2,4]])
arr

In [ ]:
np.max(arr)

In [ ]:
np.min(arr)

In [ ]:
np.sum(arr)

In [ ]:
np.mean(arr)

In [ ]:
np.std(arr)

In [ ]:
np.var(arr)

In [ ]:
np.prod(arr)

In [ ]:
np.sum(arr,axis=0) # column wise total

In [ ]:
np.sum(arr,axis = 1) # row wise total

In [ ]:
np.percentile(arr,50) # value at 50th percentile

In [ ]:
np.percentile(arr,25) # value at 25th percentile

#### Note : max,min,sum,mean,std,var

- we can find the minimum,maximum etc value within each column by specifying axis=0:

- we can find the minimum,maximum etc value within each row by specifying axis=1:

In [15]:
import numpy as np

In [16]:
a = np.array([1,2,3,np.nan])

In [17]:
np.any(a)

True

In [18]:
np.all(a)

True

In [19]:
np.isnan(a)

array([False, False, False,  True])

In [20]:
b = a[np.isnan(a,where = True,casting = 'no') == False]

In [21]:
b

array([1., 2., 3.])

In [5]:
a

array([[2, 3, 6],
       [4, 5, 6]])