## Comparision Operations


NumPy also implements comparison
operators such as < (less than) and > (greater than) as element-wise ufuncs.
The result of these comparison operators is always an **array of Boolean data type**.

 **Operators**

`== ,!= ,>= , <= ,> ,< `


In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5])

In [4]:
x<3

array([ True,  True, False, False, False])

In [5]:
x<=3

array([ True,  True,  True, False, False])

In [6]:
x!=3

array([ True,  True, False,  True,  True])

In [7]:
x == 3

array([False, False,  True, False, False])

In [8]:
# Two dimensional array
y = np.array([[2,3,5],[5,4,7]])

In [9]:
y

array([[2, 3, 5],
       [5, 4, 7]])

In [10]:
y<3

array([[ True, False, False],
       [False, False, False]])

In [11]:
y<=3

array([[ True,  True, False],
       [False, False, False]])

## Boolean Array as Masks

Boolean arrays as masks, to select particular
subsets of the data themselves.

In [15]:
y

array([[2, 3, 5],
       [5, 4, 7]])

In [18]:
#suppose we want an array of all values in the array that are less than, say, 6:
y[y<6]

array([2, 3, 5, 5, 4])

What is returned is a one-dimensional array filled with all the values that meet this
condition; in other words, all the values in positions at which the mask array is True.